materiasList = [
	{uid: "00254701", imagem: "https://unsplash.it800/601/?random", titulo: "Comissão da MP do Ensino Médio volta a ouvir educadores na quarta"},
	{uid: "00254702", imagem: "https://unsplash.it800/602/?random", titulo: "Indicado para a embaixada na Grécia será sabatinado na quinta"},
	{uid: "00254703", imagem: "https://unsplash.it800/603/?random", titulo: "CAS vota projeto que destina 70% dos recursos de acordos de leniência para a saúde"},
	{uid: "00254704", imagem: "https://unsplash.it800/604/?random", titulo: "Ministro da Saúde presta contas sobre o SUS na Comissão de Orçamento"},
	{uid: "00254705", imagem: "https://unsplash.it800/605/?random", titulo: "Fim do foro privilegiado é destaque na CCJ desta quarta-feira"},
	{uid: "00254706", imagem: "https://unsplash.it800/606/?random", titulo: "Regulamentação de jogos de azar vai beneficiar a população, acredita Ciro Nogueira"},
	{uid: "00254707", imagem: "https://unsplash.it800/607/?random", titulo: "Projeto que combate infanticídio indígena divide opiniões na CDH"},
	{uid: "00254708", imagem: "https://unsplash.it800/608/?random", titulo: "Recursos do DPVAT poderão ter destino modificado"},
	{uid: "00254709", imagem: "https://unsplash.it800/609/?random", titulo: "Comissão de Ciência e Tecnologia discute desafios da previsão do tempo"},
	{uid: "00254710", imagem: "https://unsplash.it800/590/?random", titulo: "Senadores defendem necessidade de revisão do sistema previdenciário"},
	{uid: "00254711", imagem: "https://unsplash.it800/591/?random", titulo: "Comissão de Educação vai debater projeto que cria o programa Escola sem Partido"},
	{uid: "00254712", imagem: "https://unsplash.it800/592/?random", titulo: "CAS discutirá projeto que regulamenta atividade de telemarketing"},
	{uid: "00254713", imagem: "https://unsplash.it800/593/?random", titulo: "Votação da PEC que acaba com o foro privilegiado na CCJ é destaque na agenda das Comissões"},
	{uid: "00254714", imagem: "https://unsplash.it800/594/?random", titulo: "Parlamentares participam de Conferência sobre Mudanças Climáticas no Marrocos"},
	{uid: "00254715", imagem: "https://unsplash.it800/595/?random", titulo: "CCJ pode votar nesta quarta o fim do foro privilegiado para políticos"},
	{uid: "00254716", imagem: "https://unsplash.it800/596/?random", titulo: "Discussão no Senado sobre diversidade racial no serviço público deve pautar guia para elaborar concursos"},
	{uid: "00254717", imagem: "https://unsplash.it800/597/?random", titulo: "Senadores se reúnem com ministro em Marrakech e fazem balanço da COP 22"},
	{uid: "00254718", imagem: "https://unsplash.it800/598/?random", titulo: "Reforma do ISS é o primeiro item da pauta do Plenário"},
	{uid: "00254719", imagem: "https://unsplash.it800/599/?random", titulo: "Nota pública da Presidência do Senado​"},
	{uid: "00254720", imagem: "https://unsplash.it800/600/?random", titulo: "Comissão apresenta propostas para diminuir a burocracia no Brasil"}
]